#Interval

###
POST http://localhost:8080/api/user
Content-Type: application/json
Authorization: Basic admin password

{
  "username": "yuxuan",
  "password": "12345678",
  "role": "User"
}

###
GET http://localhost:8080/api/user/yuxuan
Authorization: Basic admin password

###
POST http://localhost:8080/api/location
Content-Type: application/json
Authorization: Basic admin password

{
  "name": "Desk 1",
  "capacity": 1,
  "bookable": true
}

###
GET http://localhost:8080/api/location
Authorization: Basic admin password

###
POST http://localhost:8080/api/interval
Content-Type: application/json
Authorization: Basic yuxuan 12345678

{
  "startTime": "2021-10-24 12:30:00 +0000",
  "endTime" : "2021-10-24 16:30:00 +0000",
  "type": "Preference",
  "isRepeated": true,
  "priority": 0,
  "user": {
    "id": 1,
    "username": "yuxuan",
    "password": "12345678",
    "role": "User"
  },
  "location": {
    "id": 1,
    "name": "Desk 1",
    "capacity": 1,
    "bookable": true
  }
}

###
POST http://localhost:8080/api/interval
Content-Type: application/json
Authorization: Basic yuxuan 12345678

{
  "startTime": "2021-10-24 16:30:00 +0000",
  "endTime" : "2021-10-24 18:30:00 +0000",
  "type": "Fixed",
  "isRepeated": true,
  "priority": 0,
  "user": {
    "id": 1,
    "username": "yuxuan",
    "password": "12345678",
    "role": "User"
  },
  "location": {
    "id": 1,
    "name": "Desk 1",
    "capacity": 1,
    "bookable": true
  }
}

###
GET http://localhost:8080/api/interval
Authorization: Basic yuxuan 12345678

###
GET http://localhost:8080/api/interval/type/Preference
Authorization: Basic admin password

###
GET http://localhost:8080/api/interval/1
Authorization: Basic admin password

###
PUT http://localhost:8080/api/interval/1
Content-Type: application/json
Authorization: Basic yuxuan 12345678

{
  "startTime": "2021-10-24 10:30:00 +0000",
  "endTime" : "2021-10-24 12:30:00 +0000",
  "type": "Preference",
  "isRepeated": false,
  "priority": 2,
  "user": {
    "id": 1,
    "username": "yuxuan",
    "password": "12345678",
    "role": "User"
  },
  "location": {
    "id": 1,
    "name": "Desk 1",
    "capacity": 1,
    "bookable": true
  }
}

###
DELETE http://localhost:8080/api/interval/1
Authorization: Basic yuxuan 12345678